-- Création de la table 'manga'
CREATE TABLE manga (
    id INT,
    title VARCHAR(255),
    title_en VARCHAR(255),
    image_url VARCHAR(500),
    chapters INT,
    publishing BOOLEAN,
    published_from DATE,
    published_to DATE,
    score DECIMAL(4, 2),
    scored_by INT,
    members INT,
    favorites INT,
    author INT
);

-- Création de la table 'best_selling'
CREATE TABLE best_selling (
    manga_series VARCHAR(255),
    authors VARCHAR(500),
    publisher VARCHAR(255),
    demographic VARCHAR(100),
    no_of_volumes INT,
    serialized VARCHAR(100),
    approximate_sales_millions DECIMAL(10, 2),
    average_sales_per_volume DECIMAL(10, 2)
);

-- Table de référence des genres
CREATE TABLE genre (
    id INT,
    name VARCHAR(100),
    count INT
);

CREATE TABLE manga_genre (
    id INT,
    action INT,
    adventure INT,
    avant_garde INT,
    award_winning INT,
    boys_love INT,
    comedy INT,
    drama INT,
    fantasy INT,
    girls_love INT,
    gourmet INT,
    horror INT,
    mystery INT,
    romance INT,
    sci_fi INT,
    slice_of_life INT,
    sports INT,
    supernatural INT,
    suspense INT,
    ecchi INT,
    erotica INT,
    hentai INT,
    adult_cast INT,
    anthropomorphic INT,
    cgdct INT,
    childcare INT,
    combat_sports INT,
    crossdressing INT,
    delinquents INT,
    detective INT,
    educational INT,
    gag_humor INT,
    gore INT,
    harem INT,
    high_stakes_game INT,
    historical INT,
    idols_female INT,
    idols_male INT,
    isekai INT,
    iyashikei INT,
    love_polygon INT,
    magical_sex_shift INT,
    mahou_shoujo INT,
    martial_arts INT,
    mecha INT,
    medical INT,
    memoir INT,
    military INT,
    music INT,
    mythology INT,
    organized_crime INT,
    otaku_culture INT,
    parody INT,
    performing_arts INT,
    pets INT,
    psychological INT,
    racing INT,
    reincarnation INT,
    reverse_harem INT,
    romantic_subtext INT,
    samurai INT,
    school INT,
    showbiz INT,
    space INT,
    strategy_game INT,
    super_power INT,
    survival INT,
    team_sports INT,
    time_travel INT,
    vampire INT,
    video_game INT,
    villainess INT,
    visual_arts INT,
    workplace INT,
    josei INT,
    kids INT,
    seinen INT,
    shoujo INT,
    shounen INT
);